#!c:/Python27/python.exe

print ("Content-type: text/html\r\n\r\n")
print ('<html>')
print ('<head>')
print ('<title>Tic Tac Toe</title>')
print ('</head>')
print ('<body>')
print ('<h2>Tic Tac Toe!! </h2>')
print ('<h3>"Description of this tic tac toe game!!"</h3>')
print ("Tic-tac-toe is a paper-and-pencil game for two players, X and O, who take turns marking the spaces in a 3X3 grid.")
print ("The player who succeeds in placing three of their marks in a horizontal, vertical, or diagonal row wins the game.")
print ('<br>')
print ('<form name="pyform" method="post" action="/cgi-bin/tic_tac_toe_executable1.py"><br>')
print ("Enter the name of the first player")
print ('<br>')
print ('<br>')
print ('<input type="text" name="First"><br>')
print ("Enter the name of the second player")
print ('<br>')
print ('<input type="text" name="Second"><br>')
print ('<br><br>')
#print ("Enter your choice")
#print ('<input type="text" name="move"><br>')
#print ("Enter the name of the second player")
#print ('<input type="text" name="player_position"><br>')
#print ('<br>')
print ('<input type="submit" name="submit" value = Submit>')
print ('</form>')
print ('</body>')
print ('</html>')
